"""Initial migration

Revision ID: 326fa4404dbb
Revises: 1b8bce1e95b8
Create Date: 2024-05-05 17:52:32.491417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326fa4404dbb'
down_revision: Union[str, None] = '1b8bce1e95b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
